//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RideMe.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RideMeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RideMeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RideMe.Infrastructure.RideMeResources", typeof(RideMeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RideMe.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@glareindia.net.
        /// </summary>
        public static string CompanyRegistrationEmailAddress {
            get {
                return ResourceManager.GetString("CompanyRegistrationEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glareIndia@2014.
        /// </summary>
        public static string CompanyRegistrationEmailPassword {
            get {
                return ResourceManager.GetString("CompanyRegistrationEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string EmailAddressPort {
            get {
                return ResourceManager.GetString("EmailAddressPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string LowestCabRates {
            get {
                return ResourceManager.GetString("LowestCabRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string MinimumCabDuration {
            get {
                return ResourceManager.GetString("MinimumCabDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},
        ///
        ///Thank you for using {1} cabs. Your One Time Password for confirmation is {2}.
        /// </summary>
        public static string OTP_Email_Body {
            get {
                return ResourceManager.GetString("OTP_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cabs - One Time Password.
        /// </summary>
        public static string OTPEmailSubject {
            get {
                return ResourceManager.GetString("OTPEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 86400.
        /// </summary>
        public static string OTPExpirationDuration {
            get {
                return ResourceManager.GetString("OTPExpirationDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},
        ///
        ///Welcome to {1} cabs
        ///
        ///With your account, you can now get cabs at your doorstep at ₹{2}/km just using the {3} app.
        ///
        ///For your records, you are registered with us as:
        ///
        ///Username: {4}
        ///
        ///Please keep this information secure and do not share the password with anyone.
        ///
        ///Wishing you a very happy journey with {5} cabs.
        ///
        ///Thanks and Regards,
        ///{6} cabs.
        /// </summary>
        public static string Registration_Email_Body {
            get {
                return ResourceManager.GetString("Registration_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0} cabs.
        /// </summary>
        public static string Registration_Email_Subject {
            get {
                return ResourceManager.GetString("Registration_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.glareindia.net.
        /// </summary>
        public static string SmtpClient {
            get {
                return ResourceManager.GetString("SmtpClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ridmecabs.azurewebsites.net/token.
        /// </summary>
        public static string TokenRequestURL {
            get {
                return ResourceManager.GetString("TokenRequestURL", resourceCulture);
            }
        }
    }
}
